### ISSUE TITLE
custom answer and points on main round

### ISSUE THREAD

**Issue by PitaLife** [xKRISTOFx/familiada#40]
hello, I've tried the game made by you, but when I tried it, it turned out that the answer and the point came from you alone. can you try to custom my own answers and points ?

thanks

**Comment by xKRISTOFx** [comment]
@PitaLife You need to download programme and modify dane.csv file. Every new line is another round.

**Comment by xKRISTOFx** [comment]
All answers placed in file will be sorted automatically. Scheme is 
answer1,points1,answer2,points2,etc.

**Comment by PitaLife** [comment]
I have tried, but the error is written "Points at line 1 are not valid"

**Comment by PitaLife** [comment]
in your game only 7 answers, can you improve the answers in your game from 7 answers to 8 answers

**Comment by xKRISTOFx** [comment]
@PitaLife it is technacally possible but whole programme is created to be as close to original polish show as possible and as you can see on this ss 
![image](https://user-images.githubusercontent.com/74738911/214283991-62e2b6ce-7463-4958-92e2-c00ac3329cf4.png)
adding 8th answer will destroy original design with spacer rows. Whole thing is done to handle at most 7 answers if i even unlock error i have to create way of handling 8 answers new layout etc.

**Comment by PitaLife** [comment]
for sound effects, you can replace them with sound effects from:

1. Family Feud (USA)
2. Family Fortunes (UK)
3. Family Feud Aussie (Australia)
4. Family 100 (Indonesia)
